### ISSUE TITLE
fldist should be more responsive to wrong input

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/fluence#1095]
not sure that if this script correct:
```
(xor
    (call relay ("op" "identity") [])
    (call %init_peer_id% (returnService "run") [%last_error%])
)

```

but if to run it I get timeout:
```
dz@DESKTOP-7O591L6:/mnt/d/git/fluence/fluent-math$ fldist run_air --verbose --env testnet --log trace  --path scripts/whereiam.air  --data "{}"
client seed: CVBKFaLCRk9jL7ronFddS4ocg5Hx7rxxjsZJnruufMGd
client peerId: 12D3KooWHJ51xDuaVgkPKNHLpKosDAmENahvGPeThXP3DFZ182qc
relay peerId: 12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb
Trace: dialing to the node with client's address: 12D3KooWHJ51xDuaVgkPKNHLpKosDAmENahvGPeThXP3DFZ182qc
    at FluenceConnection.<anonymous> (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/node_modules/@fluencelabs/fluence/dist/internal/FluenceConnection.js:200:29)
    at step (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/node_modules/@fluencelabs/fluence/dist/internal/FluenceConnection.js:80:23)
    at Object.next (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/node_modules/@fluencelabs/fluence/dist/internal/FluenceConnection.js:61:53)
    at fulfilled (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/node_modules/@fluencelabs/fluence/dist/internal/FluenceConnection.js:52:58)
executing local particle {
  id: '284a5292-72a9-4b62-b141-862257fc85f8',
  init_peer_id: '12D3KooWHJ51xDuaVgkPKNHLpKosDAmENahvGPeThXP3DFZ182qc',
  timestamp: 1622366294202,
  ttl: 60000,
  script: '\n' +
    '(seq\n' +
    '    (call %init_peer_id% ("load" "load_relay") [] init_relay)\n' +
    '    \n' +
    '    (xor\n' +
    '        \n' +
    '(seq\n' +
    '    (call %init_peer_id% ("load" "load_variable") ["returnService"] returnService)\n' +
    '    \n' +
    '(seq\n' +
    '    (call %init_peer_id% ("load" "load_variable") ["relay"] relay)\n' +
    '    (xor\r\n' +
    '    (call relay ("op" "identity") [])\r\n' +
    '    (call %init_peer_id% (returnService "run") [%last_error%])\r\n' +
    ')\r\n' +
    '\n' +
    ')\n' +
    ')\n' +
    '        (xor\n' +
    '            (match init_relay ""\n' +
    '                (call %init_peer_id% ("__magic" "handle_xor") [%last_error%])\n' +
    '            )\n' +
    '            (seq \n' +
    '                (call init_relay ("op" "identity") [])\n' +
    '                (call %init_peer_id% ("__magic" "handle_xor") [%last_error%])\n' +
    '            )\n' +
    '        )\n' +
    '    )\n' +
    ')',
  signature: '',
  data: <Buffer >
}
interpreter executing particle {
  id: '284a5292-72a9-4b62-b141-862257fc85f8',
  init_peer_id: '12D3KooWHJ51xDuaVgkPKNHLpKosDAmENahvGPeThXP3DFZ182qc',
  timestamp: 1622366294202,
  ttl: 60000,
  script: '\n' +
    '(seq\n' +
    '    (call %init_peer_id% ("load" "load_relay") [] init_relay)\n' +
    '    \n' +
    '    (xor\n' +
    '        \n' +
    '(seq\n' +
    '    (call %init_peer_id% ("load" "load_variable") ["returnService"] returnService)\n' +
    '    \n' +
    '(seq\n' +
    '    (call %init_peer_id% ("load" "load_variable") ["relay"] relay)\n' +
    '    (xor\r\n' +
    '    (call relay ("op" "identity") [])\r\n' +
    '    (call %init_peer_id% (returnService "run") [%last_error%])\r\n' +
    ')\r\n' +
    '\n' +
    ')\n' +
    ')\n' +
    '        (xor\n' +
    '            (match init_relay ""\n' +
    '                (call %init_peer_id% ("__magic" "handle_xor") [%last_error%])\n' +
    '            )\n' +
    '            (seq \n' +
    '                (call init_relay ("op" "identity") [])\n' +
    '                (call %init_peer_id% ("__magic" "handle_xor") [%last_error%])\n' +
    '            )\n' +
    '        )\n' +
    '    )\n' +
    ')',
  signature: '',
  data: <Buffer >
}
inner interpreter outcome: {
  particleId: '284a5292-72a9-4b62-b141-862257fc85f8',
  ret_code: 0,
  error_message: '',
  next_peer_pks: [ '12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb' ]
}
send particle:
{
  "action": "Particle",
  "id": "284a5292-72a9-4b62-b141-862257fc85f8",
  "init_peer_id": "12D3KooWHJ51xDuaVgkPKNHLpKosDAmENahvGPeThXP3DFZ182qc",
  "timestamp": 1622366294202,
  "ttl": 60000,
  "script": "\n(seq\n    (call %init_peer_id% (\"load\" \"load_relay\") [] init_relay)\n    \n    (xor\n        \n(seq\n    (call %init_peer_id% (\"load\" \"load_variable\") [\"returnService\"] returnService)\n    \n(seq\n    (call %init_peer_id% (\"load\" \"load_variable\") [\"relay\"] relay)\n    (xor\r\n    (call relay (\"op\" 
\"identity\") [])\r\n    (call %init_peer_id% (returnService \"run\") [%last_error%])\r\n)\r\n\n)\n)\n        (xor\n            (match init_relay \"\"\n                (call %init_peer_id% (\"__magic\" \"handle_xor\") [%last_error%])\n            )\n            (seq \n                (call init_relay (\"op\" \"identity\") [])\n   
             (call %init_peer_id% (\"__magic\" \"handle_xor\") [%last_error%])\n            )\n        )\n    )\n)",
  "signature": [],
  "data": "W3siY2FsbCI6eyJleGVjdXRlZCI6IjEyRDNLb29XQlVKaWZDVGdheEFVcmNNOUp5c3FDY1M0Q1M4dGlZSDVoRXhiZFdDQW9Od2IifX0seyJjYWxsIjp7ImV4ZWN1dGVkIjoicmV0dXJuU2VydmljZSJ9fSx7ImNhbGwiOnsiZXhlY3V0ZWQiOiIxMkQzS29vV0JVSmlmQ1RnYXhBVXJjTTlKeXNxQ2NTNENTOHRpWUg1aEV4YmRXQ0FvTndiIn19LHsiY2FsbCI6eyJyZXF1ZXN0X3NlbnRfYnkiOiIxMkQzS29vV0hKNTF4RHVhVmdrUEtOSExwS29zREFtRU5haHZHUGVUaFhQM0RGWjE4MnFjIn19XQ=="
}
Particle expired. Now: 1622366354204, ttl: 60000, ts: 1622366294202
Something went wrong!
undefined
dz@DESKTOP-7O591L6:/mnt/d/git/fluence/fluent-math$
```

expected:
either it executes succes or reports error of bad air script, but not timeout

**Comment by justprosh** [comment]
Sсript is a bit incorrect, you should run either 
```
(xor
    (seq
         (call relay ("op" "identity") [])
         (call %init_peer_id% (returnService "run") [])
    )
    (call %init_peer_id% (returnService "run") [%last_error%])
)
```
or
```
(seq
    (call relay ("op" "identity") [])
    (call %init_peer_id% (returnService "run") [])
)
```

Take a look at XOR [doc](https://doc.fluence.dev/docs/knowledge_knowledge/knowledge_aquamarine/knowledge_aquamarine_air)
For now, we don't verify that some branch of the script doesn't call returnService

**Comment by folex** [comment]
@justprosh is right. 

XOR is like a `try ... catch ...` in some languages. Your script could be read like this:
```js
try {
  (call relay ("op" "identity") [])
} catch (last_error) {
  (call %init_peer_id% (returnService "run") [%last_error%])
}
```
`(op identity)` is executed without errors, and then nothing happens. `catch` branch doesn't get triggered because there's no error, and `try` branch doesn't route particle back to your fldist invocation (`init_peer_id`)

**Comment by dzmitry-lahoda** [comment]
@justprosh, thanks.

I see, i did not return anything to caller's peer, so it is reasonably timed out. But modified script(both version) still tells me:
````
dz@DESKTOP-7O591L6:/mnt/d/git/fluence/fluent-math$ fldist run_air --verbose --env testnet  --path scripts/whereiam.air  --data "{}"
client seed: 9U2ijSLSmJWX5dPBBbB4WaTStXNQJhtY2s1d4gtZ4Npq
client peerId: 12D3KooWJhS6gEXXtHnwTAGdghKkQnmGWYWiw4UKjT3hXEyMTqZk
relay peerId: 12D3KooWBUJifCTgaxAUrcM9JysqCcS4CS8tiYH5hExbdWCAoNwb
[]
Particle timed out, exiting
```
So there was no timeout, but still tells timeout.

**Comment by dzmitry-lahoda** [comment]
i am writing script which is just usual `run some code and got description where it runs` (so same could be obtained via logs trace, but just trying to have that example)

**Comment by folex** [comment]
> Particle timed out, exiting
That looks like a wrong log! Good catch :)

**Comment by folex** [comment]
> so same could be obtained via logs trace, but just trying to have that example)
trace logs on fldist wouldn't give you that info, they only say where particle is **sent** from the client. So when particle is routed between nodes (without going to client), you won't have this info in logs.

So tracing script is a good idea :) 

Btw, I've noticed you're using `--env testnet`. Be aware that if you try to compile Rust service and deploy it to testnet, that wouldn't work. Better use `--env krasnodar` or omit `--env` altogether.
